FORMAT: 1A

# シネマサンシャインチケッティングサービス

シネマサンシャインチケッティングサービスが提供するAPIは、シネマサンシャインにおける座席予約とチケット管理を扱うアプリケーションに有用なインターフェースを提供します。

## Group 組織管理サービス

### /organizations/movieTheater

#### 劇場検索 [GET]

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 200 (application/json)

    Successful operation

    + Body

            [
              {},
              {},
              {},
              {},
              {}
            ]

    + Schema

            {
              "type": "array",
              "items": {
                "type": "object",
                "description": ""
              }
            }

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 400 (application/json)

    パラメータ不適切

    + Body

### /organizations/movieTheater/{branchCode}

#### 劇場取得 [GET]

+ Parameters

    + branchCode (required)

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 200 (application/json)

    Successful operation

    + Body

            {}

    + Schema

            {
              "type": "object",
              "description": ""
            }

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 400 (application/json)

    パラメータ不適切

    + Body

## Group 注文管理サービス

### /orders/findByOrderInquiryKey

#### 注文照会 [POST]

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

            {
              "theaterCode": "occaecat consequat",
              "confirmationNumber": 87871441,
              "telephone": "id est do"
            }

    + Schema

            {
              "type": "object",
              "required": [
                "theaterCode",
                "confirmationNumber",
                "telephone"
              ],
              "properties": {
                "theaterCode": {
                  "type": "string",
                  "example": 118
                },
                "confirmationNumber": {
                  "type": "integer",
                  "example": 12345
                },
                "telephone": {
                  "type": "string",
                  "example": "09012345678"
                }
              }
            }

+ Response 200 (application/json)

    Successful operation

    + Body

            {}

    + Schema

            {
              "type": "object",
              "description": ""
            }

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

            {
              "theaterCode": "do Excepteur",
              "confirmationNumber": 39629732,
              "telephone": "Excepteur officia deserunt labore eu"
            }

    + Schema

            {
              "type": "object",
              "required": [
                "theaterCode",
                "confirmationNumber",
                "telephone"
              ],
              "properties": {
                "theaterCode": {
                  "type": "string",
                  "example": 118
                },
                "confirmationNumber": {
                  "type": "integer",
                  "example": 12345
                },
                "telephone": {
                  "type": "string",
                  "example": "09012345678"
                }
              }
            }

+ Response 400 (application/json)

    パラメータ不適切

    + Body

#### 注文検索 [GET /orders]

+ Parameters

    + sellerIds: 
    
    + customerMembershipNumbers: 
    
    + orderNumbers: 
    
    + orderStatuses: 
    
    + orderDateFrom
    
    + orderDateThrough
    
    + confirmationNumbers: 
    
    + reservedEventIdentifiers: 

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 200 (application/json)

    Successful operation

    + Body

            [
              {},
              {},
              {},
              {}
            ]

    + Schema

            {
              "type": "array",
              "items": {
                "type": "object",
                "description": ""
              }
            }

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 400 (application/json)

    パラメータ不適切

    + Body

## Group 場所管理サービス

### /places/movieTheater/{branchCode}

#### 劇場取得 [GET]

+ Parameters

    + branchCode (required)

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 200 (application/json)

    Successful operation

    + Body

            {}

    + Schema

            {
              "type": "object",
              "description": ""
            }

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 400 (application/json)

    パラメータ不適切

    + Body

### /places/movieTheater

#### 劇場検索 [GET]

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 200 (application/json)

    Successful operation

    + Body

            [
              {},
              {},
              {}
            ]

    + Schema

            {
              "type": "array",
              "items": {
                "type": "object",
                "description": ""
              }
            }

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 400 (application/json)

    パラメータ不適切

    + Body

## Group 会員プログラム管理サービス

### /programMemberships

#### 会員プログラム検索 [GET]

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 200 (application/json)

    Successful operation

    + Body

            [
              {},
              {},
              {},
              {},
              {}
            ]

    + Schema

            {
              "type": "array",
              "items": {
                "type": "object",
                "description": ""
              }
            }

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 400 (application/json)

    パラメータ不適切

    + Body

## Group イベント管理サービス

### /events/individualScreeningEvent/{identifier}

#### 上映イベント取得 [GET]

+ Parameters

    + identifier (required)

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 200 (application/json)

    Successful operation

    + Body

            {}

    + Schema

            {
              "type": "object",
              "description": ""
            }

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 400 (application/json)

    パラメータ不適切

    + Body

### /events/individualScreeningEvent

#### 上映イベント検索 [GET]

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 200 (application/json)

    Successful operation

    + Body

            [
              {}
            ]

    + Schema

            {
              "type": "array",
              "items": {
                "type": "object",
                "description": ""
              }
            }

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 400 (application/json)

    パラメータ不適切

    + Body

## Group 注文取引サービス

### /transactions/placeOrder/start

#### 注文取引開始 [POST]

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 200 (application/json)

    Successful operation

    + Body

            {}

    + Schema

            {
              "type": "object",
              "description": ""
            }

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 400 (application/json)

    パラメータ不適切

    + Body

### /transactions/placeOrder/{transactionId}/customerContact

#### 購入者情報変更 [PUT]

+ Parameters

    + transactionId (required)

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 201 (application/json)

    Successful operation

    + Body

            {}

    + Schema

            {
              "type": "object",
              "description": ""
            }

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 400 (application/json)

    パラメータ不適切

    + Body

### /transactions/placeOrder/{transactionId}/actions/authorize/seatReservation

#### 座席予約承認追加 [POST]

+ Parameters

    + transactionId (required)

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 201 (application/json)

    Successful operation

    + Body

            {}

    + Schema

            {
              "type": "object",
              "description": ""
            }

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 400 (application/json)

    パラメータ不適切

    + Body

### /transactions/placeOrder/{transactionId}/actions/authorize/seatReservation/{actionId}

#### 座席予約承認取消 [DELETE]

+ Parameters

    + transactionId (required)
    
    + actionId (required)

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 204 (application/json)

    Successful operation

    + Body

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 400 (application/json)

    パラメータ不適切

    + Body

#### 座席予約承認変更 [PATCH]

+ Parameters

    + transactionId (required)
    
    + actionId (required)

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 200 (application/json)

    Successful operation

    + Body

            {}

    + Schema

            {
              "type": "object",
              "description": ""
            }

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 400 (application/json)

    パラメータ不適切

    + Body

### /transactions/placeOrder/{transactionId}/actions/authorize/offer/programMembership

#### 会員プログラムオファー承認追加 [POST]

+ Parameters

    + transactionId (required)

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 201 (application/json)

    Successful operation

    + Body

            {}

    + Schema

            {
              "type": "object",
              "description": ""
            }

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 400 (application/json)

    パラメータ不適切

    + Body

### /transactions/placeOrder/{transactionId}/actions/authorize/offer/programMembership/{actionId}

#### 会員プログラムオファー承認取消 [DELETE]

+ Parameters

    + transactionId (required)
    
    + actionId (required)

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 204 (application/json)

    Successful operation

    + Body

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 400 (application/json)

    パラメータ不適切

    + Body

### /transactions/placeOrder/{transactionId}/actions/authorize/creditCard

#### クレジットカード決済承認追加 [POST]

+ Parameters

    + transactionId (required)

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 201 (application/json)

    Successful operation

    + Body

            {}

    + Schema

            {
              "type": "object",
              "description": ""
            }

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 400 (application/json)

    パラメータ不適切

    + Body

### /transactions/placeOrder/{transactionId}/actions/authorize/creditCard/{actionId}

#### クレジットカード決済承認取消 [DELETE]

+ Parameters

    + transactionId (required)
    
    + actionId (required)

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 204 (application/json)

    Successful operation

    + Body

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 400 (application/json)

    パラメータ不適切

    + Body

### /transactions/placeOrder/{transactionId}/actions/authorize/mvtk

#### ムビチケ割引承認追加 [POST]

+ Parameters

    + transactionId (required)

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 201 (application/json)

    Successful operation

    + Body

            {}

    + Schema

            {
              "type": "object",
              "description": ""
            }

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 400 (application/json)

    パラメータ不適切

    + Body

### /transactions/placeOrder/{transactionId}/actions/authorize/mvtk/{actionId}

#### ムビチケ割引承認取消 [DELETE]

+ Parameters

    + transactionId (required)
    
    + actionId (required)

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 204 (application/json)

    Successful operation

    + Body

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 400 (application/json)

    パラメータ不適切

    + Body

### /transactions/placeOrder/{transactionId}/actions/authorize/paymentMethod/pecorino

#### ポイント決済承認追加 [POST]

+ Parameters

    + transactionId (required)

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 201 (application/json)

    Successful operation

    + Body

            {}

    + Schema

            {
              "type": "object",
              "description": ""
            }

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 400 (application/json)

    パラメータ不適切

    + Body

### /transactions/placeOrder/{transactionId}/actions/authorize/paymentMethod/pecorino/{actionId}

#### ポイント決済承認取消 [DELETE]

+ Parameters

    + transactionId (required)
    
    + actionId (required)

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 204 (application/json)

    Successful operation

    + Body

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 400 (application/json)

    パラメータ不適切

    + Body

### /transactions/placeOrder/{transactionId}/actions/authorize/award/pecorino

#### ポイントインセンティブ承認追加 [POST]

+ Parameters

    + transactionId (required)

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 201 (application/json)

    Successful operation

    + Body

            {}

    + Schema

            {
              "type": "object",
              "description": ""
            }

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 400 (application/json)

    パラメータ不適切

    + Body

### /transactions/placeOrder/{transactionId}/actions/authorize/award/pecorino/{actionId}

#### ポイントインセンティブ承認取消 [DELETE]

+ Parameters

    + transactionId (required)
    
    + actionId (required)

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 204 (application/json)

    Successful operation

    + Body

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 400 (application/json)

    パラメータ不適切

    + Body

### /transactions/placeOrder/{transactionId}/confirm

#### 取引確定 [POST]

+ Parameters

    + transactionId (required)

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 201 (application/json)

    Successful operation

    + Body

            {}

    + Schema

            {
              "type": "object",
              "description": ""
            }

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 400 (application/json)

    パラメータ不適切

    + Body

### /transactions/placeOrder/{transactionId}/cancel

#### 取引中止 [POST]

+ Parameters

    + transactionId (required)

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 204 (application/json)

    Successful operation

    + Body

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 400 (application/json)

    パラメータ不適切

    + Body

### /transactions/placeOrder/{transactionId}/tasks/sendEmailNotification

#### メール送信タスク追加 [POST]

+ Parameters

    + transactionId (required)

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 201 (application/json)

    Successful operation

    + Body

            {}

    + Schema

            {
              "type": "object",
              "description": ""
            }

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 400 (application/json)

    パラメータ不適切

    + Body

## Group 注文返品取引サービス

### /transactions/returnOrder/start

#### 注文返品取引開始 [POST]

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 200 (application/json)

    Successful operation

    + Body

            {}

    + Schema

            {
              "type": "object",
              "description": ""
            }

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 400 (application/json)

    パラメータ不適切

    + Body

### /transactions/returnOrder/{transactionId}/confirm

#### 注文返品取引確定 [POST]

+ Parameters

    + transactionId (required)

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 201 (application/json)

    Successful operation

    + Body

            {}

    + Schema

            {
              "type": "object",
              "description": ""
            }

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 400 (application/json)

    パラメータ不適切

    + Body

## Group 口座管理サービス

### /accounts/transactions/deposit

#### 口座入金 [POST]

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 204 (application/json)

    Successful operation

    + Body

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 400 (application/json)

    パラメータ不適切

    + Body

## Group ユーザーサービス

### /people/me/contacts

#### 連絡先検索 [GET]

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 200 (application/json)

    Successful operation

    + Body

            {}

    + Schema

            {
              "type": "object",
              "description": ""
            }

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 400 (application/json)

    パラメータ不適切

    + Body

#### 連絡先更新 [PUT]

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 204 (application/json)

    Successful operation

    + Body

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 400 (application/json)

    パラメータ不適切

    + Body

### /people/me/creditCards

#### クレジットカード検索 [GET]

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 200 (application/json)

    Successful operation

    + Body

            [
              {}
            ]

    + Schema

            {
              "type": "array",
              "items": {
                "type": "object",
                "description": ""
              }
            }

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 400 (application/json)

    パラメータ不適切

    + Body

#### クレジットカード追加 [POST]

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 201 (application/json)

    Successful operation

    + Body

            {}

    + Schema

            {
              "type": "object",
              "description": ""
            }

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 400 (application/json)

    パラメータ不適切

    + Body

### /people/me/creditCards/{cardSeq}

#### クレジットカード削除 [DELETE]

+ Parameters

    + cardSeq (required)

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 204 (application/json)

    Successful operation

    + Body

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 400 (application/json)

    パラメータ不適切

    + Body

### /people/me/accounts

#### 口座検索 [GET]

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 200 (application/json)

    Successful operation

    + Body

            [
              {},
              {}
            ]

    + Schema

            {
              "type": "array",
              "items": {
                "type": "object",
                "description": ""
              }
            }

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 400 (application/json)

    パラメータ不適切

    + Body

#### 口座開設 [POST]

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 201 (application/json)

    Successful operation

    + Body

            {}

    + Schema

            {
              "type": "object",
              "description": ""
            }

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 400 (application/json)

    パラメータ不適切

    + Body

### /people/me/accounts/{accountNumber}/close

#### 口座解約 [PUT]

+ Parameters

    + accountNumber (required)

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 204 (application/json)

    Successful operation

    + Body

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 400 (application/json)

    パラメータ不適切

    + Body

### /people/me/accounts/{accountNumber}

#### 口座削除 [DELETE]

+ Parameters

    + accountNumber (required)

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 204 (application/json)

    Successful operation

    + Body

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 400 (application/json)

    パラメータ不適切

    + Body

### /people/me/accounts/{accountNumber}/actions/moneyTransfer

#### 口座取引履歴検索 [GET]

+ Parameters

    + accountNumber (required)

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 200 (application/json)

    Successful operation

    + Body

            [
              {}
            ]

    + Schema

            {
              "type": "array",
              "items": {
                "type": "object",
                "description": ""
              }
            }

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 400 (application/json)

    パラメータ不適切

    + Body

### /people/me/ownershipInfos/{goodType}

#### 所有権検索 [GET]

+ Parameters

    + goodType (required)

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 200 (application/json)

    Successful operation

    + Body

            [
              {}
            ]

    + Schema

            {
              "type": "array",
              "items": {
                "type": "object",
                "description": ""
              }
            }

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 400 (application/json)

    パラメータ不適切

    + Body

### /people/me/ownershipInfos/programMembership/register

#### 会員プログラム登録 [PUT]

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 202 (application/json)

    Successful operation

    + Body

            {}

    + Schema

            {
              "type": "object",
              "description": ""
            }

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 400 (application/json)

    パラメータ不適切

    + Body

### /people/me/ownershipInfosownershipInfos/programMembership/{identifier}/unRegister

#### 会員プログラム登録解除 [PUT]

+ Parameters

    + identifier (required)

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 202 (application/json)

    Successful operation

    + Body

            {}

    + Schema

            {
              "type": "object",
              "description": ""
            }

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 400 (application/json)

    パラメータ不適切

    + Body

